// Generated by tools/rom_pack.py — do not edit by hand.
// Raw overlay base of the "pentagon" family: rom0.bin, 16384 B in flash.
// Every variant is a run-list patch over these bytes (manifest.json).
// Regenerate: python3 tools/rom_pack.py pentagon

#pragma once
extern "C" {
extern const unsigned char gb_rom_0_pentagon_128k[];
}
