#pragma once
#include <stdint.h>
// Scorpion ZS-256 v2.94 64K ROM (page order 0=BASIC-128, 1=BASIC-48, 2=service
// monitor, 3=TR-DOS 5.03 variant). bank0/bank1 are tiny overlays over the Sinclair
// 128K halves (scorpion_overlays.h, 434+175 B); bank2 is unique code and bank3
// diffs ~30% from trdos_505d AND rom[4] already overlays that base pointer
// (MemESP::registerOverlay is keyed by base) — both stay raw (scorpion_banks.c).
extern "C" const unsigned char gb_rom_scorpion_bank2[];
extern "C" const unsigned char gb_rom_scorpion_bank3[];
// Scorpion GMX 512 KB boot ROM (8 ProfROM planes x 4 x 16K banks), embedded in
// flash on every board (GMX_IN_FLASH=1 in CMakeLists; =0 is an escape hatch) —
// QSPI (butter) PSRAM is a property of the plugged-in Pico module, so GMX is
// gated at RUNTIME by the butter probe, not per board. The linker shrinks the
// GM.DLS partition to make room (rp2350-memmap.ld __gmx_rom_in_flash). Stored deduplicated (6 banks are
// copies) and partly as overlays over ROMs already in flash (~378 KB instead of
// 512): the generated scorpion_gmx_banks.h carries the {data, overlay} binding
// table Config::requestMachine walks. Generated by `python3 tools/rom_pack.py
// gmx` (scorpion_gmx_rom.c + scorpion_gmx_banks.h); this include must stay
// AFTER roms.h has declared the base ROMs (Sinclair 128K halves, trdos_505d,
// gb_overlay_pentagon_rom0) the table points into.
#if GMX_IN_FLASH
#include "scorpion_gmx_banks.h"
// Re-registers the live GMX bank's overlay (defined in Config.cpp — the ONLY TU
// that may reference gb_rom_scorpion_gmx_banks: the Sinclair 128K bases inside
// it are header-defined internal-linkage arrays, so a second referencing TU
// embeds 32 KB of private copies whose addresses the overlay registry can never
// match). Called from gmxTapUpdate (Ports.cpp) on every GMX romInUse change.
void gmxRegisterLiveOverlay(uint8_t bank);
#endif
// Scorpion PROF-ROM v4.01 (romset R_SCORP_PROF) — 256 KB, 4 planes x 4 banks,
// stored deduplicated + partly as overlays (~181 KB; tools/rom_pack.py prof).
// This is the firmware a real ZS-1024 Turbo+ shipped with, and the one that
// drives the SMUC HDD controller: the driver lives in plane 1 bank 3. Like the
// GMX table, the {data, overlay} pairs are bound by Config::requestMachine and
// the LIVE bank's overlay is re-registered on every romInUse change.
#if PROFROM_IN_FLASH
#include "scorpion_prof_banks.h"
// Defined in Config.cpp — the ONLY TU that may reference the bank table (same
// internal-linkage trap as the GMX one above). Called from gmxTapUpdate.
void profRegisterLiveOverlay(uint8_t bank);
#endif
#include "scorpion_overlays.h"
