// Generated by tools/rom_pack.py (pack_prof) — do not edit by hand.
// Scorpion PROF-ROM v4.xx.015 (scorp4xx015_5D4BA991.ROM, CRC32 5D4BA991), 4 planes
// x 4 x 16K banks, deduplicated and partly expressed as overlays over ROMs
// the firmware already ships — see the pack_prof comment in
// tools/rom_pack.py. 230561 B in flash instead of 262144.
// Regenerate: python3 tools/rom_pack.py prof
// Include via romScorpion.h only (needs the base ROM symbols in scope).
#pragma once
extern "C" {
extern const unsigned char gb_rom_scorpion_prof_p0b2[];
extern const unsigned char gb_rom_scorpion_prof_p0b3[];
extern const unsigned char gb_rom_scorpion_prof_p1b0[];
extern const unsigned char gb_rom_scorpion_prof_p1b1[];
extern const unsigned char gb_rom_scorpion_prof_p1b2[];
extern const unsigned char gb_rom_scorpion_prof_p1b3[];
extern const unsigned char gb_rom_scorpion_prof_p2b0[];
extern const unsigned char gb_rom_scorpion_prof_p2b1[];
extern const unsigned char gb_rom_scorpion_prof_p2b2[];
extern const unsigned char gb_rom_scorpion_prof_p2b3[];
extern const unsigned char gb_rom_scorpion_prof_p3b0[];
extern const unsigned char gb_rom_scorpion_prof_p3b1[];
extern const unsigned char gb_rom_scorpion_prof_p3b2[];
extern const unsigned char gb_rom_scorpion_prof_p3b3[];
extern const unsigned char gb_overlay_scorpion_prof_p0b0[];
extern const unsigned char gb_overlay_scorpion_prof_p0b1[];
}

typedef struct { const unsigned char* data; const unsigned char* overlay; } scorpion_prof_bank_t;
// rom[plane*4+slot] binds .data (Config::requestMachine); the overlay of the
// bank live at 0x0000 is (re)registered on every romInUse change by
// gmxTapUpdate (Ports.cpp) — several banks share a base pointer, so a static
// registration cannot express this. Duplicate banks share a pointer.
static const scorpion_prof_bank_t gb_rom_scorpion_prof_banks[16] = {
    { gb_rom_0_sinclair_128k, gb_overlay_scorpion_prof_p0b0 },   // plane 0 bank 0
    { gb_rom_1_sinclair_128k, gb_overlay_scorpion_prof_p0b1 },   // plane 0 bank 1
    { gb_rom_scorpion_prof_p0b2, nullptr },   // plane 0 bank 2
    { gb_rom_scorpion_prof_p0b3, nullptr },   // plane 0 bank 3
    { gb_rom_scorpion_prof_p1b0, nullptr },   // plane 1 bank 0
    { gb_rom_scorpion_prof_p1b1, nullptr },   // plane 1 bank 1
    { gb_rom_scorpion_prof_p1b2, nullptr },   // plane 1 bank 2
    { gb_rom_scorpion_prof_p1b3, nullptr },   // plane 1 bank 3
    { gb_rom_scorpion_prof_p2b0, nullptr },   // plane 2 bank 0
    { gb_rom_scorpion_prof_p2b1, nullptr },   // plane 2 bank 1
    { gb_rom_scorpion_prof_p2b2, nullptr },   // plane 2 bank 2
    { gb_rom_scorpion_prof_p2b3, nullptr },   // plane 2 bank 3
    { gb_rom_scorpion_prof_p3b0, nullptr },   // plane 3 bank 0
    { gb_rom_scorpion_prof_p3b1, nullptr },   // plane 3 bank 1
    { gb_rom_scorpion_prof_p3b2, nullptr },   // plane 3 bank 2
    { gb_rom_scorpion_prof_p3b3, nullptr },   // plane 3 bank 3
};
