// Generated by tools/rom_pack.py (pack_gmx) — do not edit by hand.
// Scorpion GMX boot ROM "GMX Boot Rom 1.3 V5.00" (MAME gmx13500.rom, CRC32
// 47c9df88), 8 ProfROM planes x 4 x 16K banks, deduplicated and partly
// expressed as overlays over ROMs the firmware already ships — see the
// pack_gmx comment in tools/rom_pack.py. 345525 B in flash instead of 524288.
// Regenerate: python3 tools/rom_pack.py gmx
// Include via romScorpion.h only (needs the base ROM symbols in scope).
#pragma once
extern "C" {
extern const unsigned char gb_rom_scorpion_gmx_p0b0[];
extern const unsigned char gb_rom_scorpion_gmx_p0b1[];
extern const unsigned char gb_rom_scorpion_gmx_p0b2[];
extern const unsigned char gb_rom_scorpion_gmx_p0b3[];
extern const unsigned char gb_rom_scorpion_gmx_p2b0[];
extern const unsigned char gb_rom_scorpion_gmx_p2b1[];
extern const unsigned char gb_rom_scorpion_gmx_p2b3[];
extern const unsigned char gb_rom_scorpion_gmx_p4b2[];
extern const unsigned char gb_rom_scorpion_gmx_p4b3[];
extern const unsigned char gb_rom_scorpion_gmx_p5b0[];
extern const unsigned char gb_rom_scorpion_gmx_p5b1[];
extern const unsigned char gb_rom_scorpion_gmx_p5b2[];
extern const unsigned char gb_rom_scorpion_gmx_p5b3[];
extern const unsigned char gb_rom_scorpion_gmx_p6b0[];
extern const unsigned char gb_rom_scorpion_gmx_p6b1[];
extern const unsigned char gb_rom_scorpion_gmx_p6b2[];
extern const unsigned char gb_rom_scorpion_gmx_p6b3[];
extern const unsigned char gb_rom_scorpion_gmx_p7b0[];
extern const unsigned char gb_rom_scorpion_gmx_p7b1[];
extern const unsigned char gb_rom_scorpion_gmx_p7b2[];
extern const unsigned char gb_rom_scorpion_gmx_p7b3[];
extern const unsigned char gb_overlay_scorpion_gmx_p1b1[];
extern const unsigned char gb_overlay_scorpion_gmx_p1b2[];
extern const unsigned char gb_overlay_scorpion_gmx_p4b0[];
extern const unsigned char gb_overlay_scorpion_gmx_p4b1[];
}

typedef struct { const unsigned char* data; const unsigned char* overlay; } scorpion_gmx_bank_t;
// rom[plane*4+slot] binds .data (Config::requestMachine); the overlay of the
// bank live at 0x0000 is (re)registered on every romInUse change by
// gmxTapUpdate (Ports.cpp) — several banks share a base pointer, so a static
// registration cannot express this. Duplicate banks share a pointer.
static const scorpion_gmx_bank_t gb_rom_scorpion_gmx_banks[32] = {
    { gb_rom_scorpion_gmx_p0b0, nullptr },   // plane 0 bank 0
    { gb_rom_scorpion_gmx_p0b1, nullptr },   // plane 0 bank 1
    { gb_rom_scorpion_gmx_p0b2, nullptr },   // plane 0 bank 2
    { gb_rom_scorpion_gmx_p0b3, nullptr },   // plane 0 bank 3
    { gb_rom_0_sinclair_128k, gb_overlay_pentagon_rom0 },   // plane 1 bank 0
    { gb_rom_1_sinclair_128k, gb_overlay_scorpion_gmx_p1b1 },   // plane 1 bank 1
    { gb_rom_4_trdos_505d, gb_overlay_scorpion_gmx_p1b2 },   // plane 1 bank 2
    { gb_rom_4_trdos_505d, gb_overlay_scorpion_gmx_p1b2 },   // plane 1 bank 3  = bank 6
    { gb_rom_scorpion_gmx_p2b0, nullptr },   // plane 2 bank 0
    { gb_rom_scorpion_gmx_p2b1, nullptr },   // plane 2 bank 1
    { gb_rom_scorpion_gmx_p2b1, nullptr },   // plane 2 bank 2  = bank 9
    { gb_rom_scorpion_gmx_p2b3, nullptr },   // plane 2 bank 3
    { gb_rom_scorpion_gmx_p2b0, nullptr },   // plane 3 bank 0  = bank 8
    { gb_rom_scorpion_gmx_p2b1, nullptr },   // plane 3 bank 1  = bank 9
    { gb_rom_scorpion_gmx_p2b1, nullptr },   // plane 3 bank 2  = bank 9
    { gb_rom_scorpion_gmx_p2b3, nullptr },   // plane 3 bank 3  = bank 11
    { gb_rom_0_sinclair_128k, gb_overlay_scorpion_gmx_p4b0 },   // plane 4 bank 0
    { gb_rom_1_sinclair_128k, gb_overlay_scorpion_gmx_p4b1 },   // plane 4 bank 1
    { gb_rom_scorpion_gmx_p4b2, nullptr },   // plane 4 bank 2
    { gb_rom_scorpion_gmx_p4b3, nullptr },   // plane 4 bank 3
    { gb_rom_scorpion_gmx_p5b0, nullptr },   // plane 5 bank 0
    { gb_rom_scorpion_gmx_p5b1, nullptr },   // plane 5 bank 1
    { gb_rom_scorpion_gmx_p5b2, nullptr },   // plane 5 bank 2
    { gb_rom_scorpion_gmx_p5b3, nullptr },   // plane 5 bank 3
    { gb_rom_scorpion_gmx_p6b0, nullptr },   // plane 6 bank 0
    { gb_rom_scorpion_gmx_p6b1, nullptr },   // plane 6 bank 1
    { gb_rom_scorpion_gmx_p6b2, nullptr },   // plane 6 bank 2
    { gb_rom_scorpion_gmx_p6b3, nullptr },   // plane 6 bank 3
    { gb_rom_scorpion_gmx_p7b0, nullptr },   // plane 7 bank 0
    { gb_rom_scorpion_gmx_p7b1, nullptr },   // plane 7 bank 1
    { gb_rom_scorpion_gmx_p7b2, nullptr },   // plane 7 bank 2
    { gb_rom_scorpion_gmx_p7b3, nullptr },   // plane 7 bank 3
};
