// Generated by tools/rom_pack.py — do not edit by hand.
// Scorpion ZS-256 v2.95 ROM (CRC32 0C6C1EF6), the two banks that are not
// overlays: bank2 = service monitor (this is what the version number is),
// bank3 = the Scorpion TR-DOS 5.03 variant (kept raw because rom[4] already
// overlays the trdos base pointer and MemESP::registerOverlay is keyed by
// base — a second overlay on the same base cannot coexist).
// Regenerate: python3 tools/rom_pack.py scorpion

#pragma once
extern "C" {
extern const unsigned char gb_rom_scorpion_bank2[];
extern const unsigned char gb_rom_scorpion_bank3[];
}
