// Generated by tools/rom_pack.py (pack_scorpevo) — do not edit by hand.
// ScorpEvo ProfROM v4.44s for ZX-Evo (ProfRomEVO_v4s.rom, CRC32 B9A3DB83,
// plane-ordered src/scorpevo.bin CRC32 E340238A), 4 planes x 4 x 16K banks,
// deduplicated against the R_SCORP_PROF banks. 50005 B in flash instead of 262144.
// Lives in .psramroms (rp2350-memmap.ld). Regenerate: python3 tools/rom_pack.py scorpevo
// Include via romScorpion.h only, AFTER scorpion_prof_banks.h (it declares
// the ProfROM raw banks used as bases and scorpion_prof_bank_t).
#pragma once
extern "C" {
extern const unsigned char gb_rom_scorpion_evo_p0b2[];
extern const unsigned char gb_rom_scorpion_evo_p1b1[];
extern const unsigned char gb_overlay_scorpion_evo_p0b0[];
extern const unsigned char gb_overlay_scorpion_evo_p0b1[];
extern const unsigned char gb_overlay_scorpion_evo_p0b3[];
extern const unsigned char gb_overlay_scorpion_evo_p1b0[];
extern const unsigned char gb_overlay_scorpion_evo_p1b2[];
extern const unsigned char gb_overlay_scorpion_evo_p1b3[];
extern const unsigned char gb_overlay_scorpion_evo_p2b0[];
extern const unsigned char gb_overlay_scorpion_evo_p2b1[];
extern const unsigned char gb_overlay_scorpion_evo_p2b2[];
extern const unsigned char gb_overlay_scorpion_evo_p2b3[];
extern const unsigned char gb_overlay_scorpion_evo_p3b0[];
extern const unsigned char gb_overlay_scorpion_evo_p3b1[];
extern const unsigned char gb_overlay_scorpion_evo_p3b2[];
extern const unsigned char gb_overlay_scorpion_evo_p3b3[];
}

static const scorpion_prof_bank_t gb_rom_scorpion_evo_banks[16] = {
    { gb_rom_0_pentagon_128k, gb_overlay_scorpion_evo_p0b0 },   // plane 0 bank 0
    { gb_rom_1_sinclair_128k, gb_overlay_scorpion_evo_p0b1 },   // plane 0 bank 1
    { gb_rom_scorpion_evo_p0b2, nullptr },   // plane 0 bank 2
    { gb_rom_scorpion_prof_p0b3, gb_overlay_scorpion_evo_p0b3 },   // plane 0 bank 3
    { gb_rom_scorpion_prof_p1b0, gb_overlay_scorpion_evo_p1b0 },   // plane 1 bank 0
    { gb_rom_scorpion_evo_p1b1, nullptr },   // plane 1 bank 1
    { gb_rom_scorpion_prof_p1b2, gb_overlay_scorpion_evo_p1b2 },   // plane 1 bank 2
    { gb_rom_scorpion_prof_p1b3, gb_overlay_scorpion_evo_p1b3 },   // plane 1 bank 3
    { gb_rom_scorpion_prof_p2b0, gb_overlay_scorpion_evo_p2b0 },   // plane 2 bank 0
    { gb_rom_scorpion_prof_p2b1, gb_overlay_scorpion_evo_p2b1 },   // plane 2 bank 1
    { gb_rom_scorpion_prof_p2b2, gb_overlay_scorpion_evo_p2b2 },   // plane 2 bank 2
    { gb_rom_scorpion_prof_p2b3, gb_overlay_scorpion_evo_p2b3 },   // plane 2 bank 3
    { gb_rom_scorpion_prof_p3b0, gb_overlay_scorpion_evo_p3b0 },   // plane 3 bank 0
    { gb_rom_scorpion_prof_p3b1, gb_overlay_scorpion_evo_p3b1 },   // plane 3 bank 1
    { gb_rom_scorpion_prof_p3b2, gb_overlay_scorpion_evo_p3b2 },   // plane 3 bank 2
    { gb_rom_scorpion_prof_p3b3, gb_overlay_scorpion_evo_p3b3 },   // plane 3 bank 3
};
