// Generated by tools/rom_pack.py plus3div — do not edit by hand.
// The +3 (divIDE) ROM banks: what this build of the image needs of its own,
// and the names Config::requestMachine binds for the rest.
#pragma once

extern "C" {
extern const unsigned char gb_overlay_plus3div_rom1[];
extern const unsigned char gb_overlay_plus3div_rom2[];
}

#define PLUS3DIV_ROM0_OVL  gb_overlay_plus3e_rom0
#define PLUS3DIV_ROM1_OVL  gb_overlay_plus3div_rom1
#define PLUS3DIV_ROM2_BASE gb_rom_2_plus3e
#define PLUS3DIV_ROM2_OVL  gb_overlay_plus3div_rom2
#define PLUS3DIV_ROM3_OVL  gb_overlay_plus3_rom3
