// Generated by tools/rom_pack.py — do not edit by hand.
#pragma once
extern "C" {
extern const unsigned char gb_overlay_profi_bank2[];
extern const unsigned char gb_overlay_profi_bank3[];
extern const unsigned char gb_overlay_profi_bank1_pq[];
extern const unsigned char gb_overlay_profi_bank2_pq[];
extern const unsigned char gb_overlay_profi_bank3_pq[];
extern const unsigned char gb_overlay_profi_bank1_romain[];
}
