// Generated by tools/rom_pack.py — do not edit by hand.
// Raw overlay base of the "trdos" family: 504t.bin, 16384 B in flash.
// Every variant is a run-list patch over these bytes (manifest.json).
// Regenerate: python3 tools/rom_pack.py trdos

#pragma once
extern "C" {
extern const unsigned char gb_rom_4_trdos_504t[];
}
