// Generated by tools/rom_pack.py — do not edit by hand.
#pragma once
extern "C" {
extern const unsigned char gb_overlay_48k_es[];
extern const unsigned char gb_overlay_48k_byte[];
extern const unsigned char gb_overlay_48k_byte_sovmest[];
}
