// Generated by tools/rom_pack.py — do not edit by hand.
#pragma once
extern "C" {
extern const unsigned char gb_overlay_128k_es[];
extern const unsigned char gb_overlay_128k_plus2[];
extern const unsigned char gb_overlay_128k_plus2es[];
}
