// Generated by tools/rom_pack.py (pack_timex) — do not edit by hand.
// Timex TC2068: the 16 KB HOME ROM (rom[0]) and the 8 KB EX-ROM that the
// SCLD maps into any of the eight 8 KB slots when DEC bit 7 is set.
// Source: Fuse roms/tc2068-0.rom + tc2068-1.rom (= MAME ts2068_h/ts2068_x).
// Regenerate: python3 tools/rom_pack.py timex

#pragma once
extern "C" {
extern const unsigned char gb_rom_tc2068_home[];
extern const unsigned char gb_rom_tc2068_exrom[];
}
