// Generated by tools/rom_pack.py (pack_atm) — do not edit by hand.
// ATM-Turbo 1 / 2+ BIOS pages: raw SYS pages + run-list overlays over ROMs
// the firmware already ships. Atm::bindRoms() flattens them into PSRAM.
// Linked into .psramroms (rp2350-memmap.ld) — butter-PSRAM boards only.
// Regenerate: python3 tools/rom_pack.py atm

// Include from Config.cpp ONLY: the table names gb_rom_1_sinclair_128k,
// an internal-linkage array a second TU would duplicate (see romScorpion.h).
#pragma once
#include "Atm.h"   // atm_rom_page_t
extern "C" {
extern const unsigned char gb_rom_atm1_p0[];
extern const unsigned char gb_rom_atm2_p3[];
extern const unsigned char gb_rom_atm_font[];
extern const unsigned char gb_overlay_atm2x_p7[];
extern const unsigned char gb_overlay_atm1_p1[];
extern const unsigned char gb_overlay_atm1_p3[];
extern const unsigned char gb_overlay_atm2_p0[];
extern const unsigned char gb_overlay_atm2_p1[];
extern const unsigned char gb_overlay_atm2x_p0[];
extern const unsigned char gb_overlay_atm2x_p1[];
extern const unsigned char gb_overlay_atm2x_p2[];
extern const unsigned char gb_overlay_atm2x_p4[];
extern const unsigned char gb_overlay_atm2x_p5[];
extern const unsigned char gb_overlay_atm2x_p6[];
}
static const atm_rom_page_t gb_rom_atm1_pages[4] = {
    { gb_rom_atm1_p0, nullptr },   // page 0
    { gb_rom_4_trdos_504t, gb_overlay_atm1_p1 },   // page 1
    { gb_rom_0_pentagon_128k, nullptr },   // page 2
    { gb_rom_1_sinclair_128k, gb_overlay_atm1_p3 },   // page 3
};
static const atm_rom_page_t gb_rom_atm2_pages[4] = {
    { gb_rom_1_sinclair_128k, gb_overlay_atm2_p0 },   // page 0
    { gb_rom_4_trdos_504t, gb_overlay_atm2_p1 },   // page 1
    { gb_rom_0_pentagon_128k, nullptr },   // page 2
    { gb_rom_atm2_p3, nullptr },   // page 3
};
static const atm_rom_page_t gb_rom_atm2x_pages[8] = {
    { gb_rom_1_sinclair_128k, gb_overlay_atm2x_p0 },   // page 0
    { gb_rom_4_trdos_504t, gb_overlay_atm2x_p1 },   // page 1
    { nullptr, gb_overlay_atm2x_p2 },   // page 2
    { nullptr, nullptr },   // page 3
    { gb_rom_1_sinclair_128k, gb_overlay_atm2x_p4 },   // page 4
    { gb_rom_4_trdos_504t, gb_overlay_atm2x_p5 },   // page 5
    { gb_rom_0_pentagon_128k, gb_overlay_atm2x_p6 },   // page 6
    { gb_rom_atm2_p3, gb_overlay_atm2x_p7 },   // page 7
};
