/*
 * gen_opl_tabs.c — generates src/OplTabs.h, the two big YMF262 lookup tables
 * of MAME's ymf262.cpp (init_tables(), GPL-2.0+, Jarek Burczynski) as const
 * flash arrays, plus the ksl table as integers.
 *
 * MAME builds tl_tab (13*2*256 signed ints, 26 KB) and sin_tab (8*1024
 * unsigned ints, 32 KB) at runtime into .bss. On the RP2350 that RAM does not
 * exist to spare, so the same values are precomputed here and stored as
 * int16_t / uint16_t const (they fit: |tl_tab| <= 4085, sin_tab < 6656+1),
 * ~29.7 KB of flash and zero RAM. The math below is byte-for-byte MAME's —
 * do not "fix" it, regenerate with this tool if it ever needs to change:
 *
 *   gcc -O2 -o /tmp/gen_opl_tabs tools/gen_opl_tabs.c -lm && /tmp/gen_opl_tabs > src/OplTabs.h
 */

#include <stdio.h>
#include <math.h>

#define ENV_BITS   10
#define ENV_LEN    (1 << ENV_BITS)
#define ENV_STEP   (128.0 / ENV_LEN)
#define SIN_BITS   10
#define SIN_LEN    (1 << SIN_BITS)
#define SIN_MASK   (SIN_LEN - 1)
#define TL_RES_LEN 256
#define TL_TAB_LEN (13 * 2 * TL_RES_LEN)

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

static int tl_tab[TL_TAB_LEN];
static unsigned int sin_tab[SIN_LEN * 8];

int main(void) {
    int i, x, n;
    double o, m;

    /* --- tl_tab, exactly MAME ymf262.cpp init_tables() --- */
    for (x = 0; x < TL_RES_LEN; x++) {
        m = (1 << 16) / pow(2, (x + 1) * (ENV_STEP / 4.0) / 8.0);
        m = floor(m);
        n = (int)m;
        n >>= 4;
        if (n & 1) n = (n >> 1) + 1; else n = n >> 1;
        n <<= 1;
        tl_tab[x * 2 + 0] = n;
        tl_tab[x * 2 + 1] = ~tl_tab[x * 2 + 0]; /* OPL3: one's complement (differs from OPL2) */
        for (i = 1; i < 13; i++) {
            tl_tab[x * 2 + 0 + i * 2 * TL_RES_LEN] = tl_tab[x * 2 + 0] >> i;
            tl_tab[x * 2 + 1 + i * 2 * TL_RES_LEN] = ~tl_tab[x * 2 + 0 + i * 2 * TL_RES_LEN];
        }
    }

    /* --- sin_tab waveform 0 --- */
    for (i = 0; i < SIN_LEN; i++) {
        m = sin(((i * 2) + 1) * M_PI / SIN_LEN);
        if (m > 0.0) o = 8 * log(1.0 / m) / log(2.0);
        else         o = 8 * log(-1.0 / m) / log(2.0);
        o = o / (ENV_STEP / 4);
        n = (int)(2.0 * o);
        if (n & 1) n = (n >> 1) + 1; else n = n >> 1;
        sin_tab[i] = n * 2 + (m >= 0.0 ? 0 : 1);
    }

    /* --- waveforms 1..7, exactly MAME --- */
    for (i = 0; i < SIN_LEN; i++) {
        if (i & (1 << (SIN_BITS - 1))) sin_tab[1 * SIN_LEN + i] = TL_TAB_LEN;
        else                           sin_tab[1 * SIN_LEN + i] = sin_tab[i];

        sin_tab[2 * SIN_LEN + i] = sin_tab[i & (SIN_MASK >> 1)];

        if (i & (1 << (SIN_BITS - 2))) sin_tab[3 * SIN_LEN + i] = TL_TAB_LEN;
        else                           sin_tab[3 * SIN_LEN + i] = sin_tab[i & (SIN_MASK >> 2)];

        if (i & (1 << (SIN_BITS - 1))) sin_tab[4 * SIN_LEN + i] = TL_TAB_LEN;
        else                           sin_tab[4 * SIN_LEN + i] = sin_tab[i * 2];

        if (i & (1 << (SIN_BITS - 1))) sin_tab[5 * SIN_LEN + i] = TL_TAB_LEN;
        else                           sin_tab[5 * SIN_LEN + i] = sin_tab[(i * 2) & (SIN_MASK >> 1)];

        if (i & (1 << (SIN_BITS - 1))) sin_tab[6 * SIN_LEN + i] = 1;
        else                           sin_tab[6 * SIN_LEN + i] = 0;

        if (i & (1 << (SIN_BITS - 1))) x = ((SIN_LEN - 1) - i) * 16 + 1;
        else                           x = i * 16;
        if (x > TL_TAB_LEN) x = TL_TAB_LEN;
        sin_tab[7 * SIN_LEN + i] = x;
    }

    printf("// Generated by tools/gen_opl_tabs.c — do not edit by hand.\n");
    printf("// YMF262 attenuation/sine tables from MAME ymf262.cpp init_tables()\n");
    printf("// (GPL-2.0+, Jarek Burczynski), precomputed into flash const.\n");
    printf("#ifndef OplTabs_h\n#define OplTabs_h\n\n#include <inttypes.h>\n\n");

    printf("// |values| <= 4085, int16 is exact\n");
    printf("static const int16_t opl_tl_tab[%d] = {", TL_TAB_LEN);
    for (i = 0; i < TL_TAB_LEN; i++) {
        if ((i & 15) == 0) printf("\n");
        printf("%d,", tl_tab[i]);
    }
    printf("\n};\n\n");

    printf("// values <= TL_TAB_LEN (%d), uint16 is exact\n", TL_TAB_LEN);
    printf("static const uint16_t opl_sin_tab[%d] = {", SIN_LEN * 8);
    for (i = 0; i < SIN_LEN * 8; i++) {
        if ((i & 15) == 0) printf("\n");
        printf("%u,", sin_tab[i]);
    }
    printf("\n};\n\n#endif // OplTabs_h\n");
    return 0;
}
