#!/usr/bin/env python3
# rom_pack.py — pico-speccy ROM overlay packer.
#
# Many ROM variants differ from one "base" ROM by only a few hundred *positionally
# identical* bytes (e.g. TR-DOS 5.03/5.04TM vs 5.05D). Instead of shipping every
# variant as a full 16/32/64 KB array, we keep ONE base raw in flash (used via XIP)
# and store each variant as a tiny read-only OVERLAY: a sorted list of "runs"
# (offset,len,bytes) that differ from the base. The overlay lives in flash; at ROM
# read time MemESP substitutes the patched byte when the address falls inside a run
# (see src/RomOverlay.h). No RAM copy, no flash write, no reboot — on every board.
#
# This only works when the diff is POSITIONAL (same addresses). For ROMs that differ
# by insertions/relocations the run-list explodes — check the printed run count.
#
# Emits, per family, into src/roms/<fam>/ :
#   <fam>_overlays.c    — overlay blobs as C arrays (compiled into flash)
#   <fam>_overlays.h    — extern decls (included by roms.h)
#   <variant>.ovl       — raw overlay blob (artifact)
#   <base>.bin          — base ROM dump (artifact)
#   manifest.json       — human-readable family description
#
# Overlay blob layout (little-endian), matched by src/RomOverlay.h:
#   0  4  magic  "RPO1"
#   4  4  rom_len
#   8  4  nruns
#  12  .. runs[nruns] : { uint16 start, uint16 len, uint16 data_off }   (6 B each)
#  ..  .. repl[]      : replacement bytes, concatenated in run (address) order

import re, os, sys, json, struct

MAGIC = b'RPO1'
HDR = 12
RUN = 6

# ---------------------------------------------------------------- ROM extraction
_STRIP_BLOCK = re.compile(r'/\*.*?\*/', re.S)
_STRIP_LINE  = re.compile(r'//[^\n]*')
_TOK = re.compile(r'0x[0-9A-Fa-f]{1,2}\b')

def _strip(s):
    return _STRIP_LINE.sub('', _STRIP_BLOCK.sub('', s))

def load_rom(path, sym):
    # .bin = raw dump (source of truth, see <fam>/src/). .c/.h = parse the C array.
    if path.endswith('.bin'):
        return open(path, 'rb').read()
    s = _strip(open(path, encoding='latin-1').read())
    m = re.search(r'\b' + re.escape(sym) + r'\s*\[[^\]]*\]\s*=\s*\{', s)
    if not m:
        raise SystemExit("symbol %s not found in %s" % (sym, path))
    b = m.end(); e = s.index('}', b)
    return bytes(int(x, 16) for x in _TOK.findall(s[b:e]))

# ---------------------------------------------------------------- overlay codec
def make_overlay(base, tgt):
    # Source arrays are declared [rom_len] in C, so a short initializer is zero-padded
    # by the compiler. Match that exactly (NOT base-padding) so the overlay is byte-
    # identical to what the firmware would have had.
    if len(tgt) < len(base):
        tgt = tgt + b'\x00' * (len(base) - len(tgt))
    if len(base) != len(tgt):
        raise SystemExit("overlay requires variant <= base length (%d vs %d)" % (len(tgt), len(base)))
    n = len(base)
    diff = [i for i in range(n) if base[i] != tgt[i]]
    runs = []
    for i in diff:
        if runs and i == runs[-1][1] + 1:
            runs[-1][1] = i
        else:
            runs.append([i, i])
    run_recs = bytearray(); repl = bytearray(); off = 0
    for s, e in runs:
        ln = e - s + 1
        if s > 0xFFFF or ln > 0xFFFF or off > 0xFFFF:
            raise SystemExit("overlay field overflow (ROM too big for uint16 runs)")
        run_recs += struct.pack('<HHH', s, ln, off)
        repl += tgt[s:e+1]; off += ln
    blob = MAGIC + struct.pack('<II', n, len(runs)) + bytes(run_recs) + bytes(repl)
    if apply_overlay(base, blob) != tgt:
        raise SystemExit("overlay round-trip mismatch")
    return blob, len(runs), len(diff)

def apply_overlay(base, blob):
    assert blob[:4] == MAGIC
    rom_len, nruns = struct.unpack('<II', blob[4:12])
    runs = blob[HDR:HDR + nruns * RUN]
    repl = blob[HDR + nruns * RUN:]
    out = bytearray(base)
    for i in range(nruns):
        s, ln, dof = struct.unpack('<HHH', runs[i*RUN:i*RUN+RUN])
        out[s:s+ln] = repl[dof:dof+ln]
    return bytes(out[:rom_len])

# ---------------------------------------------------------------- C emitter
def _c_array(name, data):
    out = ["__attribute__((aligned(4))) const unsigned char %s[] = {" % name]
    for i in range(0, len(data), 16):
        out.append("    " + ",".join("0x%02X" % b for b in data[i:i+16]) + ",")
    out.append("};")
    return "\n".join(out)

# ---------------------------------------------------------------- family driver
def pack_family(fam, out_dir):
    os.makedirs(out_dir, exist_ok=True)
    src_dir = os.path.join(out_dir, 'src')
    base = load_rom(os.path.join(src_dir, fam['base']['name'] + '.bin'), fam['base']['sym'])

    cdata = ['// Generated by tools/rom_pack.py — do not edit by hand.',
             '#include <stdint.h>', '']
    hdr = ['// Generated by tools/rom_pack.py — do not edit by hand.', '#pragma once',
           'extern "C" {']
    report = {'id': fam['id'], 'base': fam['base']['name'], 'base_sym': fam['base']['sym'],
              'base_len': len(base), 'variants': []}

    for v in fam['variants']:
        # A variant may override the family base (e.g. Profi banks map to different
        # Sinclair 128K halves). Its base .bin must live in <fam>/src/ too.
        vbase = v.get('base', fam['base'])
        vbase_bytes = base if vbase is fam['base'] else load_rom(
            os.path.join(src_dir, vbase['name'] + '.bin'), vbase['sym'])
        tgt = load_rom(os.path.join(src_dir, v['key'] + '.bin'), v['sym'])
        blob, nruns, ndiff = make_overlay(vbase_bytes, tgt)
        osym = 'gb_overlay_%s_%s' % (fam['id'], v['key'])
        open(os.path.join(out_dir, '%s_%s.ovl' % (fam['id'], v['key'])), 'wb').write(blob)
        cdata.append(_c_array(osym, blob)); cdata.append('')
        hdr.append('extern const unsigned char %s[];' % osym)
        report['variants'].append({'name': v['name'], 'sym': v['sym'],
                                   'overlay_sym': osym, 'len': len(blob),
                                   'runs': nruns, 'diff_bytes': ndiff})
    hdr.append('}')

    open(os.path.join(out_dir, '%s_overlays.c' % fam['id']), 'w').write("\n".join(cdata) + "\n")
    open(os.path.join(out_dir, '%s_overlays.h' % fam['id']), 'w').write("\n".join(hdr) + "\n")
    open(os.path.join(out_dir, 'manifest.json'), 'w').write(json.dumps(report, indent=2) + "\n")
    return report

# ---------------------------------------------------------------- families
FAMILIES = {
    'trdos': {
        'id': 'trdos',
        'base': {'name': 'trdos_505d', 'sym': 'gb_rom_4_trdos_505d'},
        'variants': [
            {'key': '503',   'name': '5.03',   'sym': 'gb_rom_4_trdos_503'},
            {'key': '504tm', 'name': '5.04TM', 'sym': 'gb_rom_4_trdos_504tm'},
        ],
    },
    # 48K family: all variants overlay the Sinclair 48K base. byte_48k is also used
    # as rom[1] in 128Kby/128Kbg — that path now assigns the base + this overlay too.
    '48k': {
        'id': '48k',
        'base': {'name': 'sinclair_48k', 'sym': 'gb_rom_0_sinclair_48k'},
        'variants': [
            {'key': 'es',           'name': '48K Spanish', 'sym': 'gb_rom_0_48k_es'},
            {'key': 'byte',         'name': 'BYTE',        'sym': 'gb_rom_0_byte_48k'},
            {'key': 'byte_sovmest', 'name': 'BYTE compat', 'sym': 'gb_rom_0_byte_sovmest_48k'},
        ],
    },
    # 128K: only the SECOND ROM half (rom[1], the 48K BASIC core) is overlaid — it is
    # nearly identical across variants. The FIRST half (rom[0], the 128K editor/menu)
    # differs ~90% positionally between variants and stays a raw array.
    '128k': {
        'id': '128k',
        'base': {'name': 'sinclair_128k_1', 'sym': 'gb_rom_1_sinclair_128k'},
        'variants': [
            {'key': 'es',      'name': '128K Spanish', 'sym': 'gb_rom_1_128k_es'},
            {'key': 'plus2',   'name': '+2',           'sym': 'gb_rom_1_plus2'},
            {'key': 'plus2es', 'name': '+2 Spanish',   'sym': 'gb_rom_1_plus2_es'},
        ],
    },
    # Pentagon = Sinclair 128K with a 101-byte patch on rom[0]; rom[1] is identical to
    # the Sinclair 128K second half (no overlay needed). The 32K pentagon blob is gone.
    'pentagon': {
        'id': 'pentagon',
        'base': {'name': 'sinclair_128k_0', 'sym': 'gb_rom_0_sinclair_128k'},
        'variants': [
            {'key': 'rom0', 'name': 'Pentagon', 'sym': 'gb_rom_0_pentagon_128k'},
        ],
    },
    # Profi 64K (4 banks). bank0 (service) is unique and bank1 (TR-DOS variant) shares
    # the trdos_505d base with rom[4] -> both stay raw. bank2 maps to Sinclair 128K
    # rom[0], bank3 to Sinclair 128K rom[1] -> overlays.
    #
    # PQDOS romset: bank0_pq is the raw service/kernel bank (profi_pq_bank0.c),
    # currently sourced from Karabas-Pro release v25092420-romain292's
    # rom/PQDOS_041h1/bios_pqdos_patched_rtc_0.41h1.rom ("PQDOS BIOS v0.41h1 with
    # RTC fix") — ~94% different from stock bank0 (overlay would be bigger than
    # raw, so it stays a raw array). bank1_pq/bank2_pq/bank3_pq (this file) are
    # BYTE-IDENTICAL between that build and the older debug/pqdos/profi64k.rom
    # (only bank0/the BIOS kernel changed across PQDOS versions so far) and
    # overlay cheaply against the SAME bases already used above (stock bank1,
    # and the shared Sinclair 128K halves) -- 5061B + 101B + 2218B vs 48KB raw,
    # ~40KB saved. Re-run `python3 tools/rom_pack.py profi` after updating any
    # of src/roms/profi/src/bank{1,2,3}_pq.bin from a newer PQDOS build.
    'profi': {
        'id': 'profi',
        'base': {'name': 'sinclair_128k_0', 'sym': 'gb_rom_0_sinclair_128k'},
        'variants': [
            {'key': 'bank2', 'name': 'Profi bank2', 'sym': 'gb_rom_profi_bank2'},
            {'key': 'bank3', 'name': 'Profi bank3', 'sym': 'gb_rom_profi_bank3',
             'base': {'name': 'sinclair_128k_1', 'sym': 'gb_rom_1_sinclair_128k'}},
            {'key': 'bank1_pq', 'name': 'Profi bank1 (PQDOS)', 'sym': 'gb_rom_profi_pq_bank1',
             'base': {'name': 'bank1', 'sym': 'gb_rom_profi_bank1'}},
            {'key': 'bank2_pq', 'name': 'Profi bank2 (PQDOS)', 'sym': 'gb_rom_profi_pq_bank2'},
            {'key': 'bank3_pq', 'name': 'Profi bank3 (PQDOS)', 'sym': 'gb_rom_profi_pq_bank3',
             'base': {'name': 'sinclair_128k_1', 'sym': 'gb_rom_1_sinclair_128k'}},
            # Karabas-Pro ROMain (ROMSET 0) bank1: TR-DOS with ramdisk mods — 1184
            # positional diff bytes over the stock Profi bank1. The image's bank2
            # is byte-identical to stock Profi bank2 (existing overlay) and its
            # bank3 is byte-identical to plain sinclair_128k_1 (no overlay), so
            # this is the only extra piece the faithful "Karabas" romset needs.
            # Source: ROMain_ramdisk_D.rom (release v25092420-romain292) 0x4000+.
            # The _A/_B/_C/_D variants differ ONLY in 8 bank1 bytes — the
            # `LD A,(0x5D16); AND 3; CP n` drive compare that routes one drive
            # letter to the RAM-disk. _D puts the RAM-disk on D: so the really
            # mounted image stays on A: (_A hijacked A:, so TR-DOS booted the
            # RAM-disk instead of the mounted disk).
            {'key': 'bank1_romain', 'name': 'Profi bank1 (ROMain)', 'sym': 'gb_rom_profi_romain_bank1',
             'base': {'name': 'bank1', 'sym': 'gb_rom_profi_bank1'}},
        ],
    },
    # Scorpion ZS-256 64K ROM v2.94 (MAME scorp294.rom, CRC32 99f57ce1; page order
    # 0=BASIC-128, 1=BASIC-48, 2=service monitor, 3=TR-DOS 5.03 variant; pages 0-1 are
    # byte-identical to the v2.92 set). bank0 is Sinclair 128K rom[0] + 290 diff bytes
    # and bank1 is Sinclair 128K rom[1] + 115 diff bytes -> overlays. bank2 (service
    # monitor) is unique code and bank3 diffs 30% from trdos_505d — and rom[4] already
    # carries overlays on that base pointer, MemESP::registerOverlay is keyed by base —
    # so both stay raw arrays in scorpion_banks.c.
    'scorpion': {
        'id': 'scorpion',
        'base': {'name': 'sinclair_128k_0', 'sym': 'gb_rom_0_sinclair_128k'},
        'variants': [
            {'key': 'bank0', 'name': 'Scorpion bank0', 'sym': 'gb_rom_scorpion_bank0'},
            {'key': 'bank1', 'name': 'Scorpion bank1', 'sym': 'gb_rom_scorpion_bank1',
             'base': {'name': 'sinclair_128k_1', 'sym': 'gb_rom_1_sinclair_128k'}},
        ],
    },
}

def main():
    root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    os.chdir(root)
    fams = sys.argv[1:] or list(FAMILIES)
    for fid in fams:
        if fid not in FAMILIES:
            raise SystemExit("unknown family: %s (known: %s)" % (fid, ", ".join(FAMILIES)))
        rep = pack_family(FAMILIES[fid], os.path.join('src', 'roms', fid))
        tot = sum(v['len'] for v in rep['variants'])
        saved = len(rep['variants']) * rep['base_len'] - tot
        print("[%s] base=%s (%d B) + %d overlays = %d B  ->  removes %d raw arrays, saves ~%d B (%.1f KB)"
              % (rep['id'], rep['base'], rep['base_len'], len(rep['variants']), tot,
                 len(rep['variants']), saved, saved / 1024))
        for v in rep['variants']:
            print("    %-13s  overlay %d B (%d runs, %d diff bytes)"
                  % (v['name'], v['len'], v['runs'], v['diff_bytes']))

if __name__ == '__main__':
    main()
