// ZX-Evo AVR keyboard controller: the Gluk "version extension", PS/2 scancode
// log, keyboard status registers and configuration interface. Port of the
// relevant parts of tslabs/zx-evo pentevo/avr/current — rtc.c (gluk_get_reg /
// gluk_set_reg), version.c (GetVersionByte / SetVersionType), ps2.c
// (ps2keyboard_to_log / from_log / reset_log), config.c (config_interface_*).
// See ZxEvoAvr.h for the register map.
#include "ZxEvoAvr.h"

#include <string.h>
#include "Z80_JLS/z80.h"
#include "FileUtils.h"
#include "Buffer.h"

namespace {

// main.h EXT_TYPE_*
enum : uint8_t {
    EXT_BASECONF_VERSION   = 0x00,
    EXT_BOOTLOADER_VERSION = 0x01,
    EXT_PS2KEYBOARDS_LOG   = 0x02,
    EXT_RDCFG              = 0x03,
    EXT_CFGIF              = 0x0E,
    EXT_SPIFL              = 0x10,
};

// config.h CFGIF_REG_*
enum : uint8_t {
    CFGIF_REG_EXTSW         = 0x00,
    CFGIF_REG_MODES_VIDEO   = 0x01,
    CFGIF_REG_MODES_MISC    = 0x02,
    CFGIF_REG_HOTKEYS       = 0x03,
    CFGIF_REG_PAD_MODE      = 0x04,
    CFGIF_REG_PAD_KEYMAP0   = 0x05,
    CFGIF_REG_PAD_KEYMAP1   = 0x06,
    CFGIF_REG_PAD_AUTOFIRE0 = 0x07,
    CFGIF_REG_PAD_AUTOFIRE1 = 0x08,
    CFGIF_REG_PROTECT       = 0x0E,
    CFGIF_REG_COMMAND       = 0x0F,   // W; R = STATUS
};
constexpr uint8_t CFGIF_PROTECT_ENABLE      = 0x80;
constexpr uint8_t CFGIF_PAD_MAPPING_NO_KEY  = 0xFF;

constexpr uint8_t MODE_VGA          = 0x01;   // main.h modes_register: we are always VGA/HDMI
constexpr uint8_t GLUK_C_CLEAR_LOG  = 0x01;
constexpr uint8_t GLUK_C_CAPS_LED   = 0x02;
constexpr uint8_t GLUK_C_EEPROM     = 0x80;

// version.h layout: 12-byte name, 2-byte date+officiality, 2-byte CRC.
// Date bytes: [0x0C] = month[2:0]<<5 | day, [0x0D] = official<<7 | year<<1 | month[3].
// 2026-09-07 official: 0x27 / 0xB5. CRC is not checked by anything we ship.
const uint8_t kBaseVer[16] = { 'P','i','c','o','S','p','e','c','c','y',0,0, 0x27,0xB5, 0x00,0x00 };
const uint8_t kBootVer[16] = { 'P','i','c','o','B','o','o','t',0,0,0,0,     0x27,0xB5, 0x00,0x00 };

// HID usage (0x00..0x6F, 0xE0..0xE7) -> PS/2 set-2 make code. Generated by
// inverting drivers/ps2kbd/ps2kbd_mrmltr.cpp's own set-2 -> HID tables, so a
// PS/2 keyboard round-trips to the exact bytes it sent. Encoding: 0 = no code;
// bit 7 set = E0-prefixed (code = v & 0x7F) — EXCEPT 0x83, the one plain set-2
// code above 0x7F (F7), which is stored literally (no E0 code is 0x03).
const uint8_t kHidToSet2[0x70] = {
    0x00, 0x00, 0x00, 0x00, 0x1C, 0x32, 0x21, 0x23, 0x24, 0x2B, 0x34, 0x33, 0x43, 0x3B, 0x42, 0x4B,  // 00
    0x3A, 0x31, 0x44, 0x4D, 0x15, 0x2D, 0x1B, 0x2C, 0x3C, 0x2A, 0x1D, 0x22, 0x35, 0x1A, 0x16, 0x1E,  // 10
    0x26, 0x25, 0x2E, 0x36, 0x3D, 0x3E, 0x46, 0x45, 0x5A, 0x76, 0x66, 0x0D, 0x29, 0x4E, 0x55, 0x54,  // 20
    0x5B, 0x5D, 0x5D, 0x4C, 0x52, 0x0E, 0x41, 0x49, 0x4A, 0x58, 0x05, 0x06, 0x04, 0x0C, 0x03, 0x0B,  // 30
    0x83, 0x0A, 0x01, 0x09, 0x78, 0x07, 0xFC, 0x7E, 0x00, 0xF0, 0xEC, 0xFD, 0xF1, 0xE9, 0xFA, 0xF4,  // 40
    0xEB, 0xF2, 0xF5, 0x77, 0xCA, 0x7C, 0x7B, 0x79, 0xDA, 0x69, 0x72, 0x7A, 0x6B, 0x73, 0x74, 0x6C,  // 50
    0x75, 0x7D, 0x70, 0x71, 0x61, 0xAF, 0x00, 0x0F, 0x08, 0x10, 0x18, 0x20, 0x28, 0x30, 0x38, 0x40,  // 60
};
// (0x31 BACKSLASH added beside 0x32 EUROPE_1 — USB keyboards report the former;
//  0x65 APPLICATION = E0 2F, the Evo's "menu" status key.)
// HID modifiers 0xE0..0xE7: LCtrl LShift LAlt LGui RCtrl RShift RAlt RGui
const uint8_t kModToSet2[8] = { 0x14, 0x12, 0x11, 0x9F, 0x94, 0x59, 0x91, 0xA7 };

uint8_t s_ext_type = EXT_BASECONF_VERSION;
uint8_t s_regc     = 0;             // AVR-side reg C bits: CAPS LED (b1), EEPROM mode (b7)

// PS/2 log, ring semantics copied from ps2.c: start 0xFF = reset (reads 0),
// end 0xFE = armed but empty, end 0xFF = overloaded (next read returns 0xFF
// and resets). Sixteen bytes, like the AVR.
uint8_t s_log[16];
uint8_t s_log_start = 0xFF;
uint8_t s_log_end   = 0xFE;

uint8_t s_kb0 = 0;   // KB_CTRL_RTC_0: lctrl rctrl lalt ralt lshift rshift f12
uint8_t s_kb1 = 0;   // KB_CTRL_RTC_1: lwin rwin menu

// Configuration interface (session state — the AVR keeps it in EEPROM).
struct Cfg {
    uint8_t pad_mode = 0;
    uint8_t protect  = 0;
    uint8_t prev_index = 0;
    uint8_t joymap_pos = 0;
    uint8_t keymap[2][16];
    uint8_t autofire[2][16];
    Cfg() { memset(keymap, CFGIF_PAD_MAPPING_NO_KEY, sizeof keymap); memset(autofire, 0, sizeof autofire); }
} s_cfg;

// 4 KB AVR EEPROM, allocated on first use (avrconf's "Reset EEPROM" writes all
// of it). Session-only; a failed allocation reads 0xFF and drops writes.
uint8_t* s_eeprom = nullptr;
bool     s_eeprom_failed = false;

uint8_t* eeprom() {
    if (!s_eeprom && !s_eeprom_failed) {
        s_eeprom = (uint8_t*)Buffer::palloc(4096, Buffer::NEED_POINTER);
        if (s_eeprom) memset(s_eeprom, 0xFF, 4096);
        else s_eeprom_failed = true;
    }
    return s_eeprom;
}

void logReset() { s_log_start = 0xFF; }

void logPush(uint8_t b) {
    if (s_log_start == 0xFF) { s_log_end = 0xFE; s_log_start = 0; }  // ps2keyboard_parse: re-arm
    if (s_log_end == 0xFF) return;                                    // overloaded, frozen until read
    if (s_log_end == 0xFE) s_log_end = s_log_start;                   // first byte after reset
    s_log[s_log_end] = b;
    if (++s_log_end >= sizeof s_log) s_log_end = 0;
    if (s_log_end == s_log_start) s_log_end = 0xFF;                   // overload
}

uint8_t logPop() {
    if (s_log_start == 0xFF) return 0;
    if (s_log_end < sizeof s_log) {
        if (s_log_end == s_log_start) return 0;
        uint8_t r = s_log[s_log_start];
        if (++s_log_start >= sizeof s_log) s_log_start = 0;
        return r;
    }
    if (s_log_end == 0xFE) return 0;
    logReset();          // after reading the overload 0xFF the AVR resets the log
    return 0xFF;
}

uint8_t cfgifRead(uint8_t i) {
    if (s_cfg.prev_index != i) { s_cfg.joymap_pos = 0; s_cfg.prev_index = i; }
    switch (i) {
        case CFGIF_REG_MODES_VIDEO: return MODE_VGA;   // stub in the AVR too
        case CFGIF_REG_MODES_MISC:  return 0;
        case CFGIF_REG_PAD_MODE:    return s_cfg.pad_mode;
        case CFGIF_REG_PAD_KEYMAP0:
        case CFGIF_REG_PAD_KEYMAP1: {
            uint8_t p = s_cfg.joymap_pos++;
            return p < 16 ? s_cfg.keymap[i - CFGIF_REG_PAD_KEYMAP0][p] : CFGIF_PAD_MAPPING_NO_KEY;
        }
        case CFGIF_REG_PAD_AUTOFIRE0:
        case CFGIF_REG_PAD_AUTOFIRE1: {
            uint8_t p = s_cfg.joymap_pos++;
            return p < 16 ? s_cfg.autofire[i - CFGIF_REG_PAD_AUTOFIRE0][p] : CFGIF_PAD_MAPPING_NO_KEY;
        }
        case CFGIF_REG_PROTECT:     return s_cfg.protect;
        case CFGIF_REG_COMMAND:     return 0xFF;       // STATUS: stub
        default:                    return 0xFF;
    }
}

void cfgifWrite(uint8_t i, uint8_t v) {
    if (s_cfg.prev_index != i) { s_cfg.joymap_pos = 0; s_cfg.prev_index = i; }
    if ((s_cfg.protect & CFGIF_PROTECT_ENABLE) && i != CFGIF_REG_COMMAND) return;
    switch (i) {
        case CFGIF_REG_PAD_MODE:    s_cfg.pad_mode = v; break;
        case CFGIF_REG_PAD_KEYMAP0:
        case CFGIF_REG_PAD_KEYMAP1: {
            uint8_t p = s_cfg.joymap_pos++;
            if (p < 16) s_cfg.keymap[i - CFGIF_REG_PAD_KEYMAP0][p] = v;
            break;
        }
        case CFGIF_REG_PAD_AUTOFIRE0:
        case CFGIF_REG_PAD_AUTOFIRE1: {
            uint8_t p = s_cfg.joymap_pos++;
            if (p < 16) s_cfg.autofire[i - CFGIF_REG_PAD_AUTOFIRE0][p] = v;
            break;
        }
        case CFGIF_REG_PROTECT:     s_cfg.protect = v; break;
        case CFGIF_REG_COMMAND:
            // 0xF7 reboot / 0xFE reboot-to-flash: the AVR resets the FPGA. avrconf
            // follows its own command with a TS-Conf soft reset (MemConfig=4,
            // SysConfig=0, RST 0), so nothing is needed here.
            break;
        default: break;
    }
}

} // namespace

void ZxEvoAvr::reset() {
    s_ext_type = EXT_BASECONF_VERSION;
    s_regc = 0;
    logReset();
    s_kb0 = s_kb1 = 0;
    // The configuration interface and the EEPROM are the AVR's persistent state
    // and survive a power cycle of the FPGA side.
}

uint8_t ZxEvoAvr::readExt(uint8_t idx, uint8_t regA) {
    uint8_t i = idx & 0x0F;
    if (s_regc & GLUK_C_EEPROM) {
        uint8_t* e = eeprom();
        return e ? e[((uint16_t)regA << 4) | i] : 0xFF;
    }
    switch (s_ext_type) {
        case EXT_BASECONF_VERSION:   return kBaseVer[i];
        case EXT_BOOTLOADER_VERSION: return kBootVer[i];
        case EXT_PS2KEYBOARDS_LOG:   return logPop();
        case EXT_RDCFG:              return i == 0 ? MODE_VGA : 0xFF;
        case EXT_CFGIF:              return cfgifRead(i);
        case EXT_SPIFL:              return 0xFF;    // SPI flash interface: not modelled
        default:                     return 0xFF;
    }
}

void ZxEvoAvr::writeExt(uint8_t idx, uint8_t v, uint8_t regA) {
    uint8_t i = idx & 0x0F;
    if (s_regc & GLUK_C_EEPROM) {
        uint8_t* e = eeprom();
        if (e) e[((uint16_t)regA << 4) | i] = v;
        return;
    }
    // SetVersionType: index 0 always selects the type; the other fifteen belong
    // to the interface that owns the window, else alias to 0 (BaseConf compat).
    if (i == 0) { s_ext_type = v; return; }
    switch (s_ext_type) {
        case EXT_SPIFL: break;
        case EXT_CFGIF: cfgifWrite(i, v); break;
        default:        s_ext_type = v; break;
    }
}

void ZxEvoAvr::writeRegC(uint8_t v) {
    if (v & GLUK_C_CLEAR_LOG) logReset();
    if ((v ^ s_regc) & GLUK_C_CAPS_LED) s_regc ^= GLUK_C_CAPS_LED;   // LED itself not modelled
    if ((v ^ s_regc) & GLUK_C_EEPROM)   s_regc ^= GLUK_C_EEPROM;
}

uint8_t ZxEvoAvr::regCBits() {
    // b3 = SD card detected, b2 = SD write-protect, b0 = NUM LED (never lit here)
    return (FileUtils::fsMount && !FileUtils::usbRoot) ? 0x08 : 0x00;
}

uint8_t ZxEvoAvr::regD() { return s_kb0; }
uint8_t ZxEvoAvr::regE() { return s_kb1; }

void ZxEvoAvr::hidKey(uint8_t hid, bool down) {
    if (!Z80Ops::isTsconf) return;
    uint8_t v;
    if (hid >= 0xE0 && hid <= 0xE7) v = kModToSet2[hid - 0xE0];
    else if (hid < sizeof kHidToSet2) v = kHidToSet2[hid];
    else return;
    if (!v) return;
    // Status bits the AVR keeps beside the log
    switch (hid) {
        case 0xE0: s_kb0 = (s_kb0 & ~0x01) | (down ? 0x01 : 0); break;   // lctrl
        case 0xE4: s_kb0 = (s_kb0 & ~0x02) | (down ? 0x02 : 0); break;   // rctrl
        case 0xE2: s_kb0 = (s_kb0 & ~0x04) | (down ? 0x04 : 0); break;   // lalt
        case 0xE6: s_kb0 = (s_kb0 & ~0x08) | (down ? 0x08 : 0); break;   // ralt
        case 0xE1: s_kb0 = (s_kb0 & ~0x10) | (down ? 0x10 : 0); break;   // lshift
        case 0xE5: s_kb0 = (s_kb0 & ~0x20) | (down ? 0x20 : 0); break;   // rshift
        case 0x45: s_kb0 = (s_kb0 & ~0x40) | (down ? 0x40 : 0); break;   // f12
        case 0xE3: s_kb1 = (s_kb1 & ~0x01) | (down ? 0x01 : 0); break;   // lwin
        case 0xE7: s_kb1 = (s_kb1 & ~0x02) | (down ? 0x02 : 0); break;   // rwin
        case 0x65: s_kb1 = (s_kb1 & ~0x04) | (down ? 0x04 : 0); break;   // menu
        default: break;
    }
    bool ext = (v & 0x80) && v != 0x83;
    if (ext) logPush(0xE0);
    if (!down) logPush(0xF0);
    logPush(ext ? (v & 0x7F) : v);
}

void ZxEvoAvr::hidModifiers(uint8_t now, uint8_t prev) {
    uint8_t diff = now ^ prev;
    if (!diff || !Z80Ops::isTsconf) return;
    for (int b = 0; b < 8; b++)
        if (diff & (1 << b)) hidKey(0xE0 + b, (now >> b) & 1);
}
