// Generated by tools/rom_pack.py (pack_tsconf) — do not edit by hand.
// TS-Conf ROM pages that are unique bytes: the TS-BIOS service page and
// the alternative 128 service ROM. Pages 1-3 come from the trdos,
// pentagon and 128k/48k families — see the pack_tsconf comment.
// 32768 B in flash for two BIOS sets (the single 64 KB blob it replaced carried three near-duplicates of ROMs already shipped).
// Regenerate: python3 tools/rom_pack.py tsconf

#pragma once
extern "C" {
extern const unsigned char gb_rom_tsbios_p0[];
extern const unsigned char gb_rom_tsbios_gluk[];
}
